import React, { useState } from 'react'
import { useColorMode } from "@chakra-ui/color-mode";
import { Button } from '@chakra-ui/react'
import { Box, Flex, Heading, Stack, Center } from "@chakra-ui/layout";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Game from '../comp/Game'


export default function index() {
    const { colorMode, toggleColorMode } = useColorMode()
    const [ gameType, setGameType ] = useState('')

  return (
    <div className={styles.container}>
        <Head>
            <title>Tic-Tac-Toe</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Flex direction={{base:"column", md:"row"}} justifyContent={{base:"center", md: "space-between"}} alignItems="center">
            <Heading>Tic-Tac-Toe!</Heading>
            <Stack direction={{base: "column", md:"row"}} alignItems="center">
                <Button fontSize="lg" p="1" m="1" onClick={toggleColorMode}>
                    {colorMode === 'dark' ? "Dark" : "Light"} Mode on!
                </Button>
            </Stack>
        </Flex> 

        <main className={styles.main}>

            {gameType ? (
                <>
                    <Game gameType = {gameType} />
                </>
            ):(
            <>
                <Box as="button">
                    <Center boxSize="200px" onClick={() => setGameType('single')} fontSize="5em">PVE</Center>
                </Box>
                <Box as="button">
                    <Center boxSize="200px" onClick={() => setGameType('multi')} fontSize="5em">PVP</Center>
                </Box>
            </>
            )}


        </main>



    </div>


  )
}
