import { useColorMode } from "@chakra-ui/color-mode";
import { Button } from '@chakra-ui/react'
import { Box, Flex, Heading, Stack, Center } from "@chakra-ui/layout";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";


export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()

  return (
    <div className={styles.container}>
      <Head>
        <title>Tic-Tac-Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction={{base:"column", md:"row"}} justifyContent={{base:"center", md: "space-between"}} alignItems="center">
          <Heading>Tic-Tac-Toe!</Heading>
          <Stack direction={{base: "column", md:"row"}} alignItems="center">
            {isPlaying ? (
            <Box as="button" fontSize="lg" border="2px" p="1" m="1" borderRadius="5px" onClick={() => gameState()}>
                New Game
              </Box>
            ):(<></>)}
            <Button fontSize="lg" p="1" m="1" onClick={toggleColorMode}>
            {colorMode === 'dark' ? "Dark" : "Light"} Mode on!
              </Button>
          </Stack>
      </Flex>
      <main className={styles.main}>

            <>
            <Box as="button">
              <Center boxSize="200px" onClick={() => gameState('one')} fontSize="5em">Play!</Center>
            </Box>
            {/* Remove PVP option for later use when adding socket.io stuff */}
            <Box as="button">
              <Center boxSize="200px" onClick={() => gameState('two')} fontSize="5em">PVP</Center>
            </Box>
            </>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
