module.exports = {
animals: [
  'Ferret',       'Rabbit',     'Squirrel',
  'Thorny Devil', 'Guinea Pig', 'Jaguar',
  'Walrus',       'Lovebird',   'Duckbill Platypus',
  'Crocodile',    'Horse',      'Ibex',
  'Baboon',       'Doe',        'Donkey',
  'Capybara',     'Gnu',        'Cat',
  'Dromedary',    'Mynah Bird', 'Hare',
  'Fawn',         'Steer',      'Elk',
  'Eagle Owl',    'Lemur',      'Salamander',       
  'Rhinoceros',   'Woodchuck',  'Alligator',        
  'Warthog',      'Mouse',      'Addax',
  'Stallion',     'Bunny',      'Starfish',
  'Ape',          'Mole',       'Antelope',
  'Gemsbok',      'Bald Eagle', 'Koala',
  'Chinchilla',   'Jackal',     'Reindeer',
  'Orangutan',    'Aoudad',     'Cow',
  'Otter',        'Tiger',      'Gopher',
  'Oryx',         'Ocelot',     'Crow',
  'Pony',         'Jerboa',     'Giraffe',
  'Bear',         'Okapi',      'Prairie Dog',      
  'Anteater',     'Shrew',      'Gorilla',
  'Budgerigar',   'Impala',     'Seal',
  'Parakeet',     'Lamb',       'Zebra',
  'Quagga',       'Armadillo',  'Ground Hog',       
  'Rat',          'Bison',      'Dingo',
  'Panther',      'Coati',      'Beaver',
  'Marten',       'Deer',       'Bat',
  'Goat',         'Meerkat',    'Argali',
  'Pronghorn',    'Pig',        'Chimpanzee',
  'Mongoose',     'Bighorn',    'Highland Cow',
  'Mare',         'Octopus',    'Chipmunk',
  'Lizard',       'Canary',     'Dog',
  'Parrot',       'Wombat',     'Ermine',
  'Whale'
]
};
